# Smart Meter Data Ingestion

Load raw smart meter data, validate schema, and prepare for processing.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO)
print("[INFO] Libraries loaded")

[INFO] Libraries loaded

In [2]:
PROJECT_ROOT = Path.cwd().parent if "notebooks" in str(Path.cwd()) else Path.cwd()
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

print("[INFO] Paths configured")

[INFO] Paths configured

In [3]:
DATA_RAW.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

print("[INFO] Directories created")

[INFO] Directories created

In [4]:
file_path = DATA_RAW / "raw_smart_meter.csv"
df = pd.read_csv(file_path)

print("[INFO] Data loaded")

[INFO] Data loaded

In [5]:
print("[INFO] Dataset Overview")
print(f"Shape: {df.shape}")
print("\nFirst 5 records:")
df.head()

[INFO] Dataset Overview
Shape: (25000, 12)

First 5 records:

,Timestamp,Meter_ID,Zone_ID,Voltage_V,Current_A,Active_Power_kW,Reactive_Power_kW,Apparent_Power_kVA,Frequency_Hz,Sub_Meter_Kitchen,Sub_Meter_HVAC,Outdoor_Temp_C
0,2021-01-01T00:00:00,MTR-4455,South,229.53,6.806,1.394,0.715,1.567,49.973,0.062,0.116,22.85
1,2021-01-01T01:00:00,MTR-4453,West,221.13,6.167,1.227,0.618,1.374,49.990,0.000,0.133,19.89
2,2021-01-01T01:00:00,MTR-4455,South,224.79,4.391,0.880,0.451,0.989,49.968,0.000,0.000,21.05
3,2021-01-01T01:00:00,MTR-4456,East,228.27,5.439,1.104,0.493,1.209,50.041,0.041,0.110,21.65
4,2021-01-01T01:00:00,MTR-4460,East,228.88,4.121,0.842,0.375,0.921,49.967,0.085,0.047,20.74

In [6]:
print("[INFO] Schema Validation")
print("Columns:")
print(list(df.columns))
print("\nData Types:")
print(df.dtypes)

[INFO] Schema Validation
Columns:
['Timestamp', 'Meter_ID', 'Zone_ID', 'Voltage_V', 'Current_A', 'Active_Power_kW', 'Reactive_Power_kW', 'Apparent_Power_kVA', 'Frequency_Hz', 'Sub_Meter_Kitchen', 'Sub_Meter_HVAC', 'Outdoor_Temp_C']

Data Types:
Timestamp                 str
Meter_ID                  str
Zone_ID                   str
Voltage_V             float64
Current_A             float64
Active_Power_kW       float64
Reactive_Power_kW     float64
Apparent_Power_kVA    float64
Frequency_Hz          float64
Sub_Meter_Kitchen     float64
Sub_Meter_HVAC        float64
Outdoor_Temp_C        float64
dtype: object

In [7]:
print("[INFO] Data Quality Check")
print("Missing values:")
print(df.isnull().sum())
print(f"\nDuplicate rows: {df.duplicated().sum()}")

[INFO] Data Quality Check
Missing values:
Timestamp               0
Meter_ID                0
Zone_ID                 0
Voltage_V             250
Current_A               0
Active_Power_kW       250
Reactive_Power_kW       0
Apparent_Power_kVA      0
Frequency_Hz            0
Sub_Meter_Kitchen       0
Sub_Meter_HVAC          0
Outdoor_Temp_C          0
dtype: int64

Duplicate rows: 600

In [8]:
print("[INFO] Descriptive Statistics")
df.describe()

[INFO] Descriptive Statistics

,Voltage_V,Current_A,Active_Power_kW,Reactive_Power_kW,Apparent_Power_kVA,Frequency_Hz,Sub_Meter_Kitchen,Sub_Meter_HVAC,Outdoor_Temp_C
count,24750.000000,25000.000000,24750.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,230.786404,10.476743,2.645895,1.237968,2.928922,50.000084,0.248533,1.193567,29.088627
std,22.927626,7.030276,8.048825,4.968096,9.421481,0.045430,0.237971,1.233238,6.586486
min,218.500000,0.275000,0.000000,0.000000,0.000000,49.827000,0.000000,0.000000,13.830000
25%,226.790000,5.575000,1.177000,0.446000,1.273000,49.969000,0.058000,0.164000,23.520000
50%,229.340000,8.341000,1.759000,0.723000,1.907000,50.000000,0.117000,0.735000,29.190000
75%,231.967500,14.463250,3.016000,1.297000,3.298000,50.031000,0.482000,1.952000,33.840000
max,646.480000,88.315000,148.558000,92.068000,174.774000,50.179000,0.947000,5.821000,44.160000

In [9]:
if "Timestamp" in df.columns:
    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
    print("[INFO] Timestamp converted")
    print(f"Date range: {df['Timestamp'].min()} to {df['Timestamp'].max()}")

[INFO] Timestamp converted
Date range: 2021-01-01 00:00:00 to 2021-12-31 23:00:00

In [10]:
output_file = DATA_PROCESSED / "ingested_data.csv"
df.to_csv(output_file, index=False)

print("[INFO] Output saved")
print(f"File: {output_file}")
print(f"Records: {len(df):,}")
print(f"Columns: {len(df.columns)}")

[INFO] Output saved
File: C:\Smart Meter Data Systems\data\processed\ingested_data.csv
Records: 25,000
Columns: 12

# Smart Meter Data Ingestion

This notebook loads raw smart meter data, validates schema, and prepares it for processing.

In [11]:
import pandas as pd
import numpy as np
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO)
print("[INFO] Libraries loaded")

[INFO] Libraries loaded

In [12]:
PROJECT_ROOT = Path.cwd().parent if "notebooks" in str(Path.cwd()) else Path.cwd()

DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

DATA_RAW.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

print("[INFO] Paths configured")

[INFO] Paths configured

In [13]:
file_path = DATA_RAW / "raw_smart_meter.csv"

if not file_path.exists():
    raise FileNotFoundError(f"Missing dataset: {file_path}")

df = pd.read_csv(file_path)

print("[INFO] Data loaded")
print("Shape:", df.shape)

df.head()

[INFO] Data loaded
Shape: (25000, 12)

,Timestamp,Meter_ID,Zone_ID,Voltage_V,Current_A,Active_Power_kW,Reactive_Power_kW,Apparent_Power_kVA,Frequency_Hz,Sub_Meter_Kitchen,Sub_Meter_HVAC,Outdoor_Temp_C
0,2021-01-01T00:00:00,MTR-4455,South,229.53,6.806,1.394,0.715,1.567,49.973,0.062,0.116,22.85
1,2021-01-01T01:00:00,MTR-4453,West,221.13,6.167,1.227,0.618,1.374,49.990,0.000,0.133,19.89
2,2021-01-01T01:00:00,MTR-4455,South,224.79,4.391,0.880,0.451,0.989,49.968,0.000,0.000,21.05
3,2021-01-01T01:00:00,MTR-4456,East,228.27,5.439,1.104,0.493,1.209,50.041,0.041,0.110,21.65
4,2021-01-01T01:00:00,MTR-4460,East,228.88,4.121,0.842,0.375,0.921,49.967,0.085,0.047,20.74

In [14]:
print("[INFO] Columns:", list(df.columns))
print("[INFO] Data types:")
print(df.dtypes)

[INFO] Columns: ['Timestamp', 'Meter_ID', 'Zone_ID', 'Voltage_V', 'Current_A', 'Active_Power_kW', 'Reactive_Power_kW', 'Apparent_Power_kVA', 'Frequency_Hz', 'Sub_Meter_Kitchen', 'Sub_Meter_HVAC', 'Outdoor_Temp_C']
[INFO] Data types:
Timestamp                 str
Meter_ID                  str
Zone_ID                   str
Voltage_V             float64
Current_A             float64
Active_Power_kW       float64
Reactive_Power_kW     float64
Apparent_Power_kVA    float64
Frequency_Hz          float64
Sub_Meter_Kitchen     float64
Sub_Meter_HVAC        float64
Outdoor_Temp_C        float64
dtype: object

In [15]:
print("[INFO] Missing values:")
print(df.isnull().sum())

print("[INFO] Duplicate rows:", df.duplicated().sum())

[INFO] Missing values:
Timestamp               0
Meter_ID                0
Zone_ID                 0
Voltage_V             250
Current_A               0
Active_Power_kW       250
Reactive_Power_kW       0
Apparent_Power_kVA      0
Frequency_Hz            0
Sub_Meter_Kitchen       0
Sub_Meter_HVAC          0
Outdoor_Temp_C          0
dtype: int64
[INFO] Duplicate rows: 600

In [16]:
df.describe()

,Voltage_V,Current_A,Active_Power_kW,Reactive_Power_kW,Apparent_Power_kVA,Frequency_Hz,Sub_Meter_Kitchen,Sub_Meter_HVAC,Outdoor_Temp_C
count,24750.000000,25000.000000,24750.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,230.786404,10.476743,2.645895,1.237968,2.928922,50.000084,0.248533,1.193567,29.088627
std,22.927626,7.030276,8.048825,4.968096,9.421481,0.045430,0.237971,1.233238,6.586486
min,218.500000,0.275000,0.000000,0.000000,0.000000,49.827000,0.000000,0.000000,13.830000
25%,226.790000,5.575000,1.177000,0.446000,1.273000,49.969000,0.058000,0.164000,23.520000
50%,229.340000,8.341000,1.759000,0.723000,1.907000,50.000000,0.117000,0.735000,29.190000
75%,231.967500,14.463250,3.016000,1.297000,3.298000,50.031000,0.482000,1.952000,33.840000
max,646.480000,88.315000,148.558000,92.068000,174.774000,50.179000,0.947000,5.821000,44.160000

In [17]:
print("\n[INFO] First 10 records:")
print(df.head(10))

print("\n[INFO] Last 10 records:")
print(df.tail(10))

[INFO] First 10 records:
             Timestamp  Meter_ID Zone_ID  Voltage_V  Current_A  \
0  2021-01-01T00:00:00  MTR-4455   South     229.53      6.806
1  2021-01-01T01:00:00  MTR-4453    West     221.13      6.167
2  2021-01-01T01:00:00  MTR-4455   South     224.79      4.391
3  2021-01-01T01:00:00  MTR-4456    East     228.27      5.439
4  2021-01-01T01:00:00  MTR-4460    East     228.88      4.121
5  2021-01-01T02:00:00  MTR-4452    East     218.50      4.447
6  2021-01-01T02:00:00  MTR-4456    East     226.46      6.112
7  2021-01-01T02:00:00  MTR-4457    West     227.75      3.820
8  2021-01-01T03:00:00  MTR-4459   South     230.72      4.540
9  2021-01-01T03:00:00  MTR-4460    East     232.08      4.334

   Active_Power_kW  Reactive_Power_kW  Apparent_Power_kVA  Frequency_Hz  \
0            1.394              0.715               1.567        49.973
1            1.227              0.618               1.374        49.990
2            0.880              0.451               0.989        49.968
3            1.104              0.493               1.209        50.041
4            0.842              0.375               0.921        49.967
5            0.919              0.321               0.974        49.965
6            1.240              0.599               1.377        49.972
7            0.813              0.315               0.872        49.994
8            1.010              0.341               1.066        50.004
9            0.885              0.415               0.978        49.963

   Sub_Meter_Kitchen  Sub_Meter_HVAC  Outdoor_Temp_C
0              0.062           0.116           22.85
1              0.000           0.133           19.89
2              0.000           0.000           21.05
3              0.041           0.110           21.65
4              0.085           0.047           20.74
5              0.000           0.038           19.17
6              0.055           0.114           20.25
7              0.133           0.000           21.24
8              0.036           0.149           20.09
9              0.094           0.071           20.17

[INFO] Last 10 records:
                 Timestamp  Meter_ID Zone_ID  Voltage_V  Current_A  \
24990  2021-12-31T19:00:00  MTR-4460    East     229.66      6.244
24991  2021-12-31T20:00:00  MTR-4451   South     236.08      6.443
24992  2021-12-31T20:00:00  MTR-4452    East     222.95      8.320
24993  2021-12-31T20:00:00  MTR-4453    West     228.56      8.076
24994  2021-12-31T22:00:00  MTR-4450   North     222.37      7.313
24995  2021-12-31T22:00:00  MTR-4452    East     231.36      9.075
24996  2021-12-31T22:00:00  MTR-4452    East     628.64     17.032
24997  2021-12-31T22:00:00  MTR-4454   North     223.71      4.433
24998  2021-12-31T23:00:00  MTR-4452    East     225.89      9.416
24999  2021-12-31T23:00:00  MTR-4455   South     230.55      8.896

       Active_Power_kW  Reactive_Power_kW  Apparent_Power_kVA  Frequency_Hz  \
24990            1.298              0.632               1.443        49.996
24991            1.437              0.511               1.525        50.020
24992            1.705              0.658               1.827        50.042
24993            1.681              0.757               1.843        50.037
24994            1.577              0.441               1.637        50.069
24995            1.984              0.753               2.123        50.046
24996            1.984              1.229               2.334        50.046
24997            0.903              0.402               0.988        50.059
24998            1.997              0.824               2.160        50.016
24999            1.803              1.001               2.062        50.009

       Sub_Meter_Kitchen  Sub_Meter_HVAC  Outdoor_Temp_C
24990              0.632           0.140           21.37
24991              0.676           0.134           21.32
24992              0.554           0.217           22.22
24993              0.534           0.189           20.79
24994              0.517           0.334           21.45
24995              0.670           0.340           21.94
24996              0.670           0.340           21.94
24997              0.542           0.292           22.32
24998              0.531           0.212           21.32
24999              0.751           0.321           21.22

In [18]:
if "Timestamp" in df.columns:
    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
    print("[INFO] Timestamp converted")
    print("Date range:", df["Timestamp"].min(), "to", df["Timestamp"].max())

[INFO] Timestamp converted

Date range: 2021-01-01 00:00:00 to 2021-12-31 23:00:00

In [19]:
output_file = DATA_PROCESSED / "ingested_data.csv"
df.to_csv(output_file, index=False)

print("[INFO] Saved:", output_file)
print("[INFO] Records:", len(df))
print("[INFO] Columns:", len(df.columns))

[INFO] Saved:

 C:\Smart Meter Data Systems\data\processed\ingested_data.csv
[INFO] Records: 25000
[INFO] Columns: 12

# Smart Meter Data Ingestion

This notebook performs ingestion of raw smart meter data, validates structure, and prepares it for downstream processing.

In [20]:
import pandas as pd
import numpy as np
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO)
print("Libraries loaded successfully")

Libraries loaded successfully

In [21]:
PROJECT_ROOT = Path.cwd().parent if "notebooks" in str(Path.cwd()) else Path.cwd()

RAW_PATH = PROJECT_ROOT / "data" / "raw"
PROCESSED_PATH = PROJECT_ROOT / "data" / "processed"

RAW_PATH.mkdir(parents=True, exist_ok=True)
PROCESSED_PATH.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw path:", RAW_PATH)

Project root: C:\Smart Meter Data Systems
Raw path: C:\Smart Meter Data Systems\data\raw

In [22]:
file_path = RAW_PATH / "raw_smart_meter.csv"

if not file_path.exists():
    raise FileNotFoundError(f"Dataset not found at {file_path}")

df = pd.read_csv(file_path)

print("Dataset loaded successfully")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully
Shape: (25000, 12)

,Timestamp,Meter_ID,Zone_ID,Voltage_V,Current_A,Active_Power_kW,Reactive_Power_kW,Apparent_Power_kVA,Frequency_Hz,Sub_Meter_Kitchen,Sub_Meter_HVAC,Outdoor_Temp_C
0,2021-01-01T00:00:00,MTR-4455,South,229.53,6.806,1.394,0.715,1.567,49.973,0.062,0.116,22.85
1,2021-01-01T01:00:00,MTR-4453,West,221.13,6.167,1.227,0.618,1.374,49.990,0.000,0.133,19.89
2,2021-01-01T01:00:00,MTR-4455,South,224.79,4.391,0.880,0.451,0.989,49.968,0.000,0.000,21.05
3,2021-01-01T01:00:00,MTR-4456,East,228.27,5.439,1.104,0.493,1.209,50.041,0.041,0.110,21.65
4,2021-01-01T01:00:00,MTR-4460,East,228.88,4.121,0.842,0.375,0.921,49.967,0.085,0.047,20.74

In [23]:
print("Columns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Columns:
['Timestamp', 'Meter_ID', 'Zone_ID', 'Voltage_V', 'Current_A', 'Active_Power_kW', 'Reactive_Power_kW', 'Apparent_Power_kVA', 'Frequency_Hz', 'Sub_Meter_Kitchen', 'Sub_Meter_HVAC', 'Outdoor_Temp_C']

Data Types:
Timestamp                 str
Meter_ID                  str
Zone_ID                   str
Voltage_V             float64
Current_A             float64
Active_Power_kW       float64
Reactive_Power_kW     float64
Apparent_Power_kVA    float64
Frequency_Hz          float64
Sub_Meter_Kitchen     float64
Sub_Meter_HVAC        float64
Outdoor_Temp_C        float64
dtype: object

In [24]:
missing_values = df.isnull().sum()

print("Missing Values:")
print(missing_values)
print(f"\nTotal missing: {missing_values.sum()}")

Missing Values:
Timestamp               0
Meter_ID                0
Zone_ID                 0
Voltage_V             250
Current_A               0
Active_Power_kW       250
Reactive_Power_kW       0
Apparent_Power_kVA      0
Frequency_Hz            0
Sub_Meter_Kitchen       0
Sub_Meter_HVAC          0
Outdoor_Temp_C          0
dtype: int64

Total missing: 500

In [25]:
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")
if duplicates > 0:
    print(f"Percentage: {duplicates/len(df)*100:.2f}%")

Duplicate rows: 600
Percentage: 2.40%

In [26]:
print("Basic Statistics:")
df.describe()

Basic Statistics:

,Voltage_V,Current_A,Active_Power_kW,Reactive_Power_kW,Apparent_Power_kVA,Frequency_Hz,Sub_Meter_Kitchen,Sub_Meter_HVAC,Outdoor_Temp_C
count,24750.000000,25000.000000,24750.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,230.786404,10.476743,2.645895,1.237968,2.928922,50.000084,0.248533,1.193567,29.088627
std,22.927626,7.030276,8.048825,4.968096,9.421481,0.045430,0.237971,1.233238,6.586486
min,218.500000,0.275000,0.000000,0.000000,0.000000,49.827000,0.000000,0.000000,13.830000
25%,226.790000,5.575000,1.177000,0.446000,1.273000,49.969000,0.058000,0.164000,23.520000
50%,229.340000,8.341000,1.759000,0.723000,1.907000,50.000000,0.117000,0.735000,29.190000
75%,231.967500,14.463250,3.016000,1.297000,3.298000,50.031000,0.482000,1.952000,33.840000
max,646.480000,88.315000,148.558000,92.068000,174.774000,50.179000,0.947000,5.821000,44.160000

In [27]:
print("First 10 records:")
print(df.head(10))

print("\nLast 10 records:")
print(df.tail(10))

First 10 records:
             Timestamp  Meter_ID Zone_ID  Voltage_V  Current_A  \
0  2021-01-01T00:00:00  MTR-4455   South     229.53      6.806
1  2021-01-01T01:00:00  MTR-4453    West     221.13      6.167
2  2021-01-01T01:00:00  MTR-4455   South     224.79      4.391
3  2021-01-01T01:00:00  MTR-4456    East     228.27      5.439
4  2021-01-01T01:00:00  MTR-4460    East     228.88      4.121
5  2021-01-01T02:00:00  MTR-4452    East     218.50      4.447
6  2021-01-01T02:00:00  MTR-4456    East     226.46      6.112
7  2021-01-01T02:00:00  MTR-4457    West     227.75      3.820
8  2021-01-01T03:00:00  MTR-4459   South     230.72      4.540
9  2021-01-01T03:00:00  MTR-4460    East     232.08      4.334

   Active_Power_kW  Reactive_Power_kW  Apparent_Power_kVA  Frequency_Hz  \
0            1.394              0.715               1.567        49.973
1            1.227              0.618               1.374        49.990
2            0.880              0.451               0.989        49.968
3            1.104              0.493               1.209        50.041
4            0.842              0.375               0.921        49.967
5            0.919              0.321               0.974        49.965
6            1.240              0.599               1.377        49.972
7            0.813              0.315               0.872        49.994
8            1.010              0.341               1.066        50.004
9            0.885              0.415               0.978        49.963

   Sub_Meter_Kitchen  Sub_Meter_HVAC  Outdoor_Temp_C
0              0.062           0.116           22.85
1              0.000           0.133           19.89
2              0.000           0.000           21.05
3              0.041           0.110           21.65
4              0.085           0.047           20.74
5              0.000           0.038           19.17
6              0.055           0.114           20.25
7              0.133           0.000           21.24
8              0.036           0.149           20.09
9              0.094           0.071           20.17

Last 10 records:
                 Timestamp  Meter_ID Zone_ID  Voltage_V  Current_A  \
24990  2021-12-31T19:00:00  MTR-4460    East     229.66      6.244
24991  2021-12-31T20:00:00  MTR-4451   South     236.08      6.443
24992  2021-12-31T20:00:00  MTR-4452    East     222.95      8.320
24993  2021-12-31T20:00:00  MTR-4453    West     228.56      8.076
24994  2021-12-31T22:00:00  MTR-4450   North     222.37      7.313
24995  2021-12-31T22:00:00  MTR-4452    East     231.36      9.075
24996  2021-12-31T22:00:00  MTR-4452    East     628.64     17.032
24997  2021-12-31T22:00:00  MTR-4454   North     223.71      4.433
24998  2021-12-31T23:00:00  MTR-4452    East     225.89      9.416
24999  2021-12-31T23:00:00  MTR-4455   South     230.55      8.896

       Active_Power_kW  Reactive_Power_kW  Apparent_Power_kVA  Frequency_Hz  \
24990            1.298              0.632               1.443        49.996
24991            1.437              0.511               1.525        50.020
24992            1.705              0.658               1.827        50.042
24993            1.681              0.757               1.843        50.037
24994            1.577              0.441               1.637        50.069
24995            1.984              0.753               2.123        50.046
24996            1.984              1.229               2.334        50.046
24997            0.903              0.402               0.988        50.059
24998            1.997              0.824               2.160        50.016
24999            1.803              1.001               2.062        50.009

       Sub_Meter_Kitchen  Sub_Meter_HVAC  Outdoor_Temp_C
24990              0.632           0.140           21.37
24991              0.676           0.134           21.32
24992              0.554           0.217           22.22
24993              0.534           0.189           20.79
24994              0.517           0.334           21.45
24995              0.670           0.340           21.94
24996              0.670           0.340           21.94
24997              0.542           0.292           22.32
24998              0.531           0.212           21.32
24999              0.751           0.321           21.22

In [28]:
if "Timestamp" in df.columns:
    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
    print("Timestamp converted to datetime")
    print(df["Timestamp"].dtype)
else:
    print("No Timestamp column found")
    print("Available columns:", df.columns.tolist())

Timestamp converted to datetime
datetime64[us]

In [29]:
output_file = PROCESSED_PATH / "ingested_data.csv"

df.to_csv(output_file, index=False)

print(f"Data saved to: {output_file}")
print(f"File size: {output_file.stat().st_size / 1024:.2f} KB")

Data saved to: C:\Smart Meter Data Systems\data\processed\ingested_data.csv
File size: 2214.82 KB

# 01 - Smart Meter Data Ingestion

## Overview
This notebook covers:
- Loading raw smart meter data from CSV
- Schema validation
- Initial data exploration
- Data quality assessment
- Summary statistics

## 1. Setup and Imports

In [30]:
import pandas as pd
import numpy as np
from pathlib import Path
import logging
from datetime import datetime
import json

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

print("Imports successful")

Imports successful

## 2. Configure Paths

In [31]:
# Setup project paths
PROJECT_ROOT = Path.cwd().parent if 'notebooks' in str(Path.cwd()) else Path.cwd()
DATA_RAW = PROJECT_ROOT / 'data' / 'raw'
DATA_PROCESSED = PROJECT_ROOT / 'data' / 'processed'

# Create directories
DATA_RAW.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

print(f"Project Root: {PROJECT_ROOT}")
print(f"Raw Data Dir: {DATA_RAW}")
print(f"Processed Data Dir: {DATA_PROCESSED}")

Project Root: C:\Smart Meter Data Systems
Raw Data Dir: C:\Smart Meter Data Systems\data\raw
Processed Data Dir: C:\Smart Meter Data Systems\data\processed

## 3. Load Raw Data

In [32]:
# Find and load the raw smart meter data
raw_file = DATA_RAW / 'raw_smart_meter.csv'

if not raw_file.exists():
    raise FileNotFoundError(f"Raw data file not found: {raw_file}")

print(f"Loading data from: {raw_file}")
df = pd.read_csv(raw_file)

print(f"\n[CHECK]“ Data loaded successfully!")
print(f"  Shape: {df.shape[0]:,} rows Ã— {df.shape[1]} columns")
print(f"  Memory: {df.memory_usage(deep=True).sum() / 1024 / 1024:.2f} MB")

Loading data from: C:\Smart Meter Data Systems\data\raw\raw_smart_meter.csv

[CHECK]“ Data loaded successfully!
  Shape: 25,000 rows Ã— 12 columns
  Memory: 6.55 MB

## 4. Schema Validation

In [33]:
# Display schema information
print("\n=== SCHEMA INFORMATION ===")
print(f"\nColumn Names: {list(df.columns)}")
print(f"\nData Types:\n{df.dtypes}")

# Schema validation
required_columns = ['Timestamp', 'Meter_ID', 'Zone', 'Active_Power_kW', 'Reactive_Power_kVAR']
missing_cols = [col for col in required_columns if col not in df.columns]

if missing_cols:
    print(f"\nâš  WARNING: Missing required columns: {missing_cols}")
else:
    print(f"\n[CHECK]“ All required columns present")

=== SCHEMA INFORMATION ===

Column Names: ['Timestamp', 'Meter_ID', 'Zone_ID', 'Voltage_V', 'Current_A', 'Active_Power_kW', 'Reactive_Power_kW', 'Apparent_Power_kVA', 'Frequency_Hz', 'Sub_Meter_Kitchen', 'Sub_Meter_HVAC', 'Outdoor_Temp_C']

Data Types:
Timestamp                 str
Meter_ID                  str
Zone_ID                   str
Voltage_V             float64
Current_A             float64
Active_Power_kW       float64
Reactive_Power_kW     float64
Apparent_Power_kVA    float64
Frequency_Hz          float64
Sub_Meter_Kitchen     float64
Sub_Meter_HVAC        float64
Outdoor_Temp_C        float64
dtype: object

âš  WARNING: Missing required columns: ['Zone', 'Reactive_Power_kVAR']

## 5. Initial Data Exploration

In [34]:
# Display first records
print("\n=== FIRST 5 RECORDS ===")
print(df.head())

print("\n=== LAST 5 RECORDS ===")
print(df.tail())

print("\n=== BASIC INFO ===")
print(df.info())

=== FIRST 5 RECORDS ===
             Timestamp  Meter_ID Zone_ID  Voltage_V  Current_A  \
0  2021-01-01T00:00:00  MTR-4455   South     229.53      6.806
1  2021-01-01T01:00:00  MTR-4453    West     221.13      6.167
2  2021-01-01T01:00:00  MTR-4455   South     224.79      4.391
3  2021-01-01T01:00:00  MTR-4456    East     228.27      5.439
4  2021-01-01T01:00:00  MTR-4460    East     228.88      4.121

   Active_Power_kW  Reactive_Power_kW  Apparent_Power_kVA  Frequency_Hz  \
0            1.394              0.715               1.567        49.973
1            1.227              0.618               1.374        49.990
2            0.880              0.451               0.989        49.968
3            1.104              0.493               1.209        50.041
4            0.842              0.375               0.921        49.967

   Sub_Meter_Kitchen  Sub_Meter_HVAC  Outdoor_Temp_C
0              0.062           0.116           22.85
1              0.000           0.133           19.89
2              0.000           0.000           21.05
3              0.041           0.110           21.65
4              0.085           0.047           20.74

=== LAST 5 RECORDS ===
                 Timestamp  Meter_ID Zone_ID  Voltage_V  Current_A  \
24995  2021-12-31T22:00:00  MTR-4452    East     231.36      9.075
24996  2021-12-31T22:00:00  MTR-4452    East     628.64     17.032
24997  2021-12-31T22:00:00  MTR-4454   North     223.71      4.433
24998  2021-12-31T23:00:00  MTR-4452    East     225.89      9.416
24999  2021-12-31T23:00:00  MTR-4455   South     230.55      8.896

       Active_Power_kW  Reactive_Power_kW  Apparent_Power_kVA  Frequency_Hz  \
24995            1.984              0.753               2.123        50.046
24996            1.984              1.229               2.334        50.046
24997            0.903              0.402               0.988        50.059
24998            1.997              0.824               2.160        50.016
24999            1.803              1.001               2.062        50.009

       Sub_Meter_Kitchen  Sub_Meter_HVAC  Outdoor_Temp_C
24995              0.670           0.340           21.94
24996              0.670           0.340           21.94
24997              0.542           0.292           22.32
24998              0.531           0.212           21.32
24999              0.751           0.321           21.22

=== BASIC INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Timestamp           25000 non-null  str
 1   Meter_ID            25000 non-null  str
 2   Zone_ID             25000 non-null  str
 3   Voltage_V           24750 non-null  float64
 4   Current_A           25000 non-null  float64
 5   Active_Power_kW     24750 non-null  float64
 6   Reactive_Power_kW   25000 non-null  float64
 7   Apparent_Power_kVA  25000 non-null  float64
 8   Frequency_Hz        25000 non-null  float64
 9   Sub_Meter_Kitchen   25000 non-null  float64
 10  Sub_Meter_HVAC      25000 non-null  float64
 11  Outdoor_Temp_C      25000 non-null  float64
dtypes: float64(9), str(3)
memory usage: 2.3 MB
None

## 6. Data Quality Assessment

In [35]:
# Null values analysis
print("\n=== NULL VALUES ===")
null_counts = df.isnull().sum()
null_pct = (df.isnull().sum() / len(df) * 100).round(2)
null_df = pd.DataFrame({
    'Column': null_counts.index,
    'Null_Count': null_counts.values,
    'Null_Percentage': null_pct.values
}).sort_values('Null_Count', ascending=False)

print(null_df[null_df['Null_Count'] > 0])
if null_df['Null_Count'].sum() == 0:
    print("No null values found [CHECK]“")

=== NULL VALUES ===
            Column  Null_Count  Null_Percentage
3        Voltage_V         250              1.0
5  Active_Power_kW         250              1.0

In [36]:
# Duplicate analysis
print("\n=== DUPLICATE RECORDS ===")
total_duplicates = df.duplicated().sum()
complete_duplicates = df.duplicated(subset=['Timestamp', 'Meter_ID']).sum()

print(f"Complete row duplicates: {total_duplicates}")
print(f"Meter-Timestamp duplicates: {complete_duplicates}")

if total_duplicates > 0:
    print(f"\nDuplicate percentage: {total_duplicates/len(df)*100:.2f}%")
else:
    print("[CHECK]“ No duplicates found")

=== DUPLICATE RECORDS ===
Complete row duplicates: 600
Meter-Timestamp duplicates: 1250

Duplicate percentage: 2.40%

## 7. Summary Statistics

In [37]:
# Numerical columns statistics
print("\n=== NUMERICAL SUMMARY ===")
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
print(df[numeric_cols].describe().round(2))

=== NUMERICAL SUMMARY ===
       Voltage_V  Current_A  Active_Power_kW  Reactive_Power_kW  \
count   24750.00   25000.00         24750.00           25000.00
mean      230.79      10.48             2.65               1.24
std        22.93       7.03             8.05               4.97
min       218.50       0.28             0.00               0.00
25%       226.79       5.58             1.18               0.45
50%       229.34       8.34             1.76               0.72
75%       231.97      14.46             3.02               1.30
max       646.48      88.32           148.56              92.07

       Apparent_Power_kVA  Frequency_Hz  Sub_Meter_Kitchen  Sub_Meter_HVAC  \
count            25000.00      25000.00           25000.00        25000.00
mean                 2.93         50.00               0.25            1.19
std                  9.42          0.05               0.24            1.23
min                  0.00         49.83               0.00            0.00
25%                  1.27         49.97               0.06            0.16
50%                  1.91         50.00               0.12            0.74
75%                  3.30         50.03               0.48            1.95
max                174.77         50.18               0.95            5.82

       Outdoor_Temp_C
count        25000.00
mean            29.09
std              6.59
min             13.83
25%             23.52
50%             29.19
75%             33.84
max             44.16

In [38]:
# Categorical columns summary
print("\n=== CATEGORICAL SUMMARY ===")
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

for col in categorical_cols:
    unique_count = df[col].nunique()
    print(f"\n{col}:")
    print(f"  Unique values: {unique_count}")
    if unique_count <= 10:
        print(f"  Value counts:\n{df[col].value_counts()}")

=== CATEGORICAL SUMMARY ===

Timestamp:
  Unique values: 8347

Meter_ID:
  Unique values: 11

Zone_ID:
  Unique values: 4
  Value counts:
Zone_ID
South    6816
East     6816
North    6810
West     4558
Name: count, dtype: int64

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_91028\1972185421.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

## 8. Time Series Analysis

In [39]:
# Parse timestamp if needed
if 'Timestamp' in df.columns:
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')
    
    print("\n=== TIME SERIES INFO ===")
    print(f"Date Range: {df['Timestamp'].min()} to {df['Timestamp'].max()}")
    print(f"Duration: {df['Timestamp'].max() - df['Timestamp'].min()}")
    print(f"Frequency: {df['Timestamp'].dtype}")
    print(f"\nRecords per day: {len(df) / ((df['Timestamp'].max() - df['Timestamp'].min()).days or 1):.0f}")

=== TIME SERIES INFO ===
Date Range: 2021-01-01 00:00:00 to 2021-12-31 23:00:00
Duration: 364 days 23:00:00
Frequency: datetime64[us]

Records per day: 69

## 9. Meter and Zone Distribution

In [40]:
# Meter distribution
if 'Meter_ID' in df.columns:
    print("\n=== METER DISTRIBUTION ===")
    print(f"Unique meters: {df['Meter_ID'].nunique()}")
    print(f"\nRecords per meter:")
    print(df['Meter_ID'].value_counts().head(10))

# Zone distribution
if 'Zone' in df.columns:
    print("\n=== ZONE DISTRIBUTION ===")
    print(f"Unique zones: {df['Zone'].nunique()}")
    print(f"\nZone breakdown:")
    print(df['Zone'].value_counts())

=== METER DISTRIBUTION ===
Unique meters: 11

Records per meter:
Meter_ID
MTR-4453    2281
MTR-4451    2281
MTR-4457    2277
MTR-4460    2276
MTR-4458    2276
MTR-4450    2273
MTR-4452    2271
MTR-4456    2269
MTR-4459    2269
MTR-4455    2266
Name: count, dtype: int64

## 10. Generate Ingestion Report

In [41]:
# Create ingestion report
ingestion_report = {
    'timestamp': datetime.now().isoformat(),
    'file_path': str(raw_file),
    'total_records': len(df),
    'total_columns': len(df.columns),
    'columns': list(df.columns),
    'data_types': df.dtypes.astype(str).to_dict(),
    'null_values': df.isnull().sum().to_dict(),
    'duplicate_records': int(df.duplicated().sum()),
    'memory_mb': float(df.memory_usage(deep=True).sum() / 1024 / 1024),
    'numeric_columns': numeric_cols,
    'categorical_columns': categorical_cols
}

print("\n=== INGESTION REPORT ===")
print(json.dumps(ingestion_report, indent=2, default=str))

# Save report
report_file = DATA_PROCESSED / 'ingestion_report.json'
with open(report_file, 'w') as f:
    json.dump(ingestion_report, f, indent=2, default=str)

print(f"\n[CHECK]“ Report saved to: {report_file}")

=== INGESTION REPORT ===
{
  "timestamp": "2026-04-19T00:11:53.655092",
  "file_path": "C:\\Smart Meter Data Systems\\data\\raw\\raw_smart_meter.csv",
  "total_records": 25000,
  "total_columns": 12,
  "columns": [
    "Timestamp",
    "Meter_ID",
    "Zone_ID",
    "Voltage_V",
    "Current_A",
    "Active_Power_kW",
    "Reactive_Power_kW",
    "Apparent_Power_kVA",
    "Frequency_Hz",
    "Sub_Meter_Kitchen",
    "Sub_Meter_HVAC",
    "Outdoor_Temp_C"
  ],
  "data_types": {
    "Timestamp": "datetime64[us]",
    "Meter_ID": "str",
    "Zone_ID": "str",
    "Voltage_V": "float64",
    "Current_A": "float64",
    "Active_Power_kW": "float64",
    "Reactive_Power_kW": "float64",
    "Apparent_Power_kVA": "float64",
    "Frequency_Hz": "float64",
    "Sub_Meter_Kitchen": "float64",
    "Sub_Meter_HVAC": "float64",
    "Outdoor_Temp_C": "float64"
  },
  "null_values": {
    "Timestamp": 0,
    "Meter_ID": 0,
    "Zone_ID": 0,
    "Voltage_V": 250,
    "Current_A": 0,
    "Active_Power_kW": 250,
    "Reactive_Power_kW": 0,
    "Apparent_Power_kVA": 0,
    "Frequency_Hz": 0,
    "Sub_Meter_Kitchen": 0,
    "Sub_Meter_HVAC": 0,
    "Outdoor_Temp_C": 0
  },
  "duplicate_records": 600,
  "memory_mb": 4.924543380737305,
  "numeric_columns": [
    "Voltage_V",
    "Current_A",
    "Active_Power_kW",
    "Reactive_Power_kW",
    "Apparent_Power_kVA",
    "Frequency_Hz",
    "Sub_Meter_Kitchen",
    "Sub_Meter_HVAC",
    "Outdoor_Temp_C"
  ],
  "categorical_columns": [
    "Timestamp",
    "Meter_ID",
    "Zone_ID"
  ]
}

[CHECK]“ Report saved to: C:\Smart Meter Data Systems\data\processed\ingestion_report.json

## 11. Export Summary

In [42]:
print("\n" + "="*80)
print("DATA INGESTION SUMMARY")
print("="*80)
print(f"[CHECK]“ Successfully loaded {len(df):,} records from {raw_file.name}")
print(f"[CHECK]“ Schema validated with {len(df.columns)} columns")
print(f"[CHECK]“ Data quality checks completed")
print(f"[CHECK]“ Ingestion report generated")
print(f"\nNext: Proceed to data cleaning and validation notebook")
print("="*80)

================================================================================
DATA INGESTION SUMMARY
================================================================================
[CHECK]“ Successfully loaded 25,000 records from raw_smart_meter.csv
[CHECK]“ Schema validated with 12 columns
[CHECK]“ Data quality checks completed
[CHECK]“ Ingestion report generated

Next: Proceed to data cleaning and validation notebook
================================================================================